name: Linting

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.4

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.2

      # Runs yarn install and caches the packages
      - uses: bahmutov/npm-install@v1

      - name: Test
        run: yarn run lint:test